line-length = 120

[format]
# https://docs.astral.sh/ruff/settings/#format
line-ending = "lf"  # Use UNIX `\n` line endings for all files

[lint]
# https://docs.astral.sh/ruff/rules/
select = [
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "I",    # isort
    "NPY",  # numpy
    "PL",   # pylint
    "UP",   # pyupgrade
    "W",    # pycodestyle warnings
]
exclude = ["tests/*"]

[lint.per-file-ignores]
"*" = ["D102", "D107", "FA102", "ANN101", "FBT001", "FBT002"]

[lint.pylint]
max-args = 15