model: uncrtaints  # Type of architecture to use. Can be one of: (utae/unet3d/fpn/convlstm/convgru/uconvlstm/buconvlstm)",
experiment_name: UnCRtainTS_bs_7_MGNLL_experiment # Name of the current experiment

# flags specific to CIRCA
batch_size: 7
num_workers: 12                        # Number of data loading workers 
loss: MGNLL                           # Image reconstruction loss to utilize [l1|l2|GNLL|MGNLL]
epochs: 70

data:
    #hdf5_file: "/home/SPeillet/Downloads/data/circa_cloud_removal.hdf5"  # Path to HDF5 file containing the data
    hdf5_file: "/var/data/datasets/circa_cloud_removal.hdf5"
    shuffle: false                                  # Whether to shuffle the data
    use_sar: true                               # Whether to include Sentinel-1 SAR data
    channels: "all"                                # Which channels to include ('all' or specific subset)
    compute_cloud_mask: false                      # Whether to compute cloud masks on the fly
#    max_samples_count: 10        # count of data (sub-)samples to take
#    max_samples_frac: 0.05                # fraction of data (sub-)samples to take
